name: MAIN Workflow

run-name: "${{ github.event.pull_request.title || github.event.head_commit.message || github.actor == 'github-actions[bot]' && format('Code Freeze {0} Workflow in {1} {2}', github.event.repository.name, github.ref_type, github.ref_name) || format('MAIN {0} Workflow in {1} {2} by {3}', github.event.repository.name, github.ref_type, github.ref_name, github.actor) }}"

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - "main"
      - release-[0-9]+.[0-9]+
    paths-ignore:
      - ".github/**"
      - "CHANGELOG.md"

  workflow_dispatch:
    inputs:
      skip_lint_test:
        description: "Skip lint and test jobs?"
        required: false
        default: false
        type: boolean
      skip_build:
        description: "Skip Build jobs?"
        required: false
        default: false
        type: boolean
      skip_deploy:
        description: "Skip Deploy jobs?"
        required: false
        default: false
        type: boolean
      enable_push_build:
        description: "Enable push build?"
        required: false
        default: true
        type: boolean

jobs:
  deploy_container:
    name: Deploy ${{ github.event.repository.name }} container
    uses: ./.github/workflows/workflow1.yaml
    strategy:
      fail-fast: false
    with:
      SERVICE_NAME: "Test Service"
      ENV_FILE: ".envs.json"
      #   CLIENT: |
      #     - CLIENT: "gel"
      #       ENVIRONMENT: "dev1"
      #       S3_BUCKET: "gel-dev-ecs-envfiles"
      #       ECS_CLUSTER: "cloudos-cluster-dev"
      #       AWS_PROFILE: "gel_cloudos_dev"
      CLIENT: |
        {
        "include":
            [
                {
                    "CLIENT": "gel",
                    "ENVIRONMENT": "dev1",
                    "S3_BUCKET": "gel-dev-ecs-envfiles",
                    "ECS_CLUSTER": "cloudos-cluster-dev",
                    "AWS_PROFILE": "gel_cloudos_dev"
                }
            ]
        }
    secrets: inherit
